# Generated by Django 4.1 on 2022-09-09 05:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('6ca5c11c-3b90-46ba-aff1-331df11d483d'), editable=False, primary_key=True, serialize=False),
        ),
    ]
