# Generated by Django 4.1 on 2022-09-09 05:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_todo_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('d7a43cef-69bf-429b-8b86-419510e46685'), editable=False, primary_key=True, serialize=False),
        ),
    ]
