# Generated by Django 4.1 on 2022-09-09 05:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_todo_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('586d41b7-0e19-4b08-93e4-cef61e654fea'), editable=False, primary_key=True, serialize=False),
        ),
    ]
