# Generated by Django 4.1 on 2022-09-09 05:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_todo_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('67089bce-4456-4fa0-b1c2-f026c6690c6e'), editable=False, primary_key=True, serialize=False),
        ),
    ]
